name: Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. Please describe the problem and your proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's the current pain point?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: dropdown
    id: workspace
    attributes:
      label: Affected Workspace
      description: Which workspace would this feature affect?
      options:
        - 'packages/shared'
        - 'packages/database'
        - 'packages/auth'
        - 'packages/ai-integrations'
        - 'apps/api'
        - 'apps/web'
        - 'apps/mobile-main'
        - 'apps/desktop'
        - 'apps/marketing'
        - 'Root / Monorepo tooling'
        - 'Multiple / Cross-cutting'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered.
    validations:
      required: false

  - type: input
    id: prd
    attributes:
      label: Related PRD
      description: If this relates to an existing PRD, reference it here.
      placeholder: 'PRD-005'
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples.
    validations:
      required: false
